services:
  db:
    image: postgres
    container_name: db_students
    restart: always
    ports:
      - "1234:5432"
    env_file:
      - .env.test

  sorteador_app:
    container_name: sorteador_cicd_app
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env.test
